### ISSUE TITLE
Questionnaire can not be created from template.

### ISSUE THREAD

**Issue by korbinib** [ds-wizard/ds-wizard#220] opened 2021-08-19 10:04 UTC
**Describe the bug**
Questionnaire can not be created from template.

**How to reproduce**
Steps to reproduce the problem:
1. Go to 'Create Project'
2. Click on 'From Template'
3. Select any template
4. Provide Title
5. Click 'Save'
4. See error: 'Questionnaire could not be created.'

**Expected behavior**
Questionnaire generated

**DS Wizard deployment:**
 - Instance elixir-no.ds-wizard.org v3.2.0~ef49335
 - Browser Chromium 92.0, Firefox 91.0

**Additional context**

**Comment by MarekSuchanek** [comment] 2021-08-19 10:41
Hi @korbinib, indeed this seems to be a bug. It is caused by having "Custom only" in Settings > Projects. In this case the "From Template" is hidden for users with Researcher role, but should be probably hidden also for Data stewards and Admins.

Can you for now solve it by changing your settings to "Templates & Custom" (or "Template only")?

We will discuss the solution internally, create a JIRA task and link it here (please do not close the issue yet).

**Comment by korbinib** [comment] 2021-08-19 13:44
Hi thanks @MarekSuchanek,  that was easy. Seems I missed to change the setting back. Maybe it would help to change the error message or hide it as you suggested.

**Comment by MarekSuchanek** [comment] 2021-08-20 12:52
It is now in our JIRA and it will be fixed in `3.3.0` release: DSW-1166

**Comment by MarekSuchanek** [comment] 2021-09-13 18:53
This has been fixed in `3.3.0` release... closing the issue.

**Closed** 2021-09-13 18:53 UTC
Labels: Bug
