### ISSUE TITLE
Document and preview on html questionnaire report fails

### ISSUE THREAD

**Issue by korbinib** [ds-wizard/ds-wizard#226] opened 2021-12-09 14:28 UTC
**Describe the bug**
Document and preview on html questionnaire report fails with:

> Failed to build final document Exception: KeyError Message: '8cedcf93-7676-4397-b3fc-a81167ff1853'

**How to reproduce**
Steps to reproduce the problem:
1. create questionnaire from life science KM
2. start to fill
3. create document/preview with 'questionnaire report' template as html
4. error

json 'questionnaire report' export/preview works
8cedcf93-7676-4397-b3fc-a81167ff1853 is not filled in

**Expected behavior**
preview/export document

**DS Wizard deployment:**
 - Instance [elixir-si.ds-wizard.org](https://elixir-si.ds-wizard.org)

**Comment by MarekSuchanek** [comment] 2021-12-09 14:40
Hi @korbinib, are any tags selected in the project?

**Comment by korbinib** [comment] 2021-12-09 14:43
No, I don't think so. We have several reports of similar behaviour across instances and KMs, but it does not reproduce reliably.

**Comment by MarekSuchanek** [comment] 2021-12-09 14:50
OK, so for the same project with the same replies it sometimes fails and sometimes works?

**Comment by korbinib** [comment] 2021-12-09 14:50
No it fails reliably for the same project it seems.

**Comment by MarekSuchanek** [comment] 2021-12-09 14:57
Could you please send me the link (can be privately on Slack).

**Comment by MarekSuchanek** [comment] 2021-12-09 16:48
In ELIXIR-SI, the issue has been caused by use of tags and a bug in document worker: DSW-1247 will be fixed today and patch version 3.6.1 will be released.

**Comment by MarekSuchanek** [comment] 2021-12-09 19:11
The new version is released and it has been verified that it solves the issue.

**Closed by MarekSuchanek** 2021-12-09 19:11 UTC
Labels: Bug
