### ISSUE TITLE
Exported km cannot be imported

### ISSUE THREAD

**Issue by talavis** [ds-wizard/ds-wizard#185] opened 2020-02-12 06:17 UTC
We have a KM (the main one developed by us) that can be used without any trouble, but after export it cannot be imported again. The error message in the frontend is `Importing package failed.` and in the backend `[Error] expected String, encountered Null`.

A copy of version 1.2.0 of the km is attached. The latest is 1.2.2 (trying to upgrade it was the reason we found the bug), but as 1.2.0 had the same problem with less data, that one is included instead.

It was possible to export and import the same KM (1.2.0) back in version 1.10 of the backend (running 2.0 now).

Running (`sed 's/"text": null/"text": ""/g'`) made it possible to import the km, but as it changed 114 (1.2.0) entries I'm afraid I cannot tell which entry was the problem.

[SciLifeLab_SciLifeLab-DMP_1.2.0.km.zip](https://github.com/ds-wizard/ds-wizard/files/4190097/SciLifeLab_SciLifeLab-DMP_1.2.0.km.zip)

**Comment by MarekSuchanek** [comment] 2020-02-14 10:06
The problem is that event with UUID `c5481a8e-62bd-41d9-9df9-c8d69db5241c` (AddChapterEvent) is using `"text": null` which seems to be allowed since metamodel version 5 but you have version 4 in the file... 

We will look deeper what was the reason, thanks for reporting...

There are two solutions currently:
- Change `"metamodelVersion": 5` for the last package (I am sending that as an attachment)
- Change the `"text"` for this single event as you did with `sed`

**Comment by talavis** [comment] 2020-02-14 13:10
Would it help you if I can provide the old kms from the database? I have db dumps dating back to middle of November.

**Comment by MarekSuchanek** [comment] 2020-02-14 15:54
Thank you very much. It won't be necessary in the end. There is an inconsistency with Wizard itself and metamodel migrator component that was caused "between" version 4 and version 5 (Wizard uses optional chapter text since 4 and migrator since 5). I will fix it for the next release - tracking in Jira: https://ds-wizard.atlassian.net/browse/DSW-632

**Comment by MarekSuchanek** [comment] 2020-02-23 11:13
It works with the fix - it will be released in 2.1.0

**Closed by MarekSuchanek** 2020-02-23 11:13 UTC
Labels: In Jira
